#ifndef __VERSION_H__
#define __VERSION_H__
#define VER_MAJOR 0
#define VER_MINOR 12
#define VER_RELEASE_STAR 0
#define VER_RELEASE_PROF 0
#define VER_RELEASE_FRAG 0
#define VER_RELEASE_SIM 0
#define VER_BUILD 0

#define VERSION_STAR VER_MAJOR.VER_MINOR.VER_RELEASE_STAR.VER_BUILD
#define VERSION_PROF VER_MAJOR.VER_MINOR.VER_RELEASE_PROF.VER_BUILD
#define VERSION_FRAG VER_MAJOR.VER_MINOR.VER_RELEASE_FRAG.VER_BUILD
#define VERSION_SIM VER_MAJOR.VER_MINOR.VER_RELEASE_SIM.VER_BUILD

#endif
